easy_admin:
  entities:
    Tag:
      class: App\Entity\Tag
      list:
        title: "All tags"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','name','products','createdAt']
        filters: ['products']
      form:
        fields:
          - {property: 'name', css_class: 'col-md-5'}
      show:
        fields:
          - {property: 'name'}
          - {property: 'products'}
          - {property: 'createdAt', type_options: { widget: 'single_text' }}

