<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9rTjrU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9rTjrU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9rTjrU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9rTjrU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV9rTjrU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V9rTjrU',
    'container.build_id' => 'd239cca4',
    'container.build_time' => 1586295442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9rTjrU');
