easy_admin:
  site_name: ' <em style ="font-size:80%">Admin Test Js</em>'
  design:
    assets:
      css:
        - '/css/bootstrap-tags/tagsinput.css'
      js:
        - '/js/admin/bootstrap-tags/tagsinput.js'
    form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
    number: '%.2f'
  list:
    batch_actions: ['delete']
